### ISSUE TITLE
Is this the official implemention of ECCV2018 paper "Deep Cross-Modal Projection Learning for Image-Text Matching"?

### ISSUE THREAD

**Issue by FlyingRoastDuck** [labyrinth7x/Deep-Cross-Modal-Projection-Learning-for-Image-Text-Matching#1]

**Comment by labyrinth7x** [comment]
The official implementation of the paper is [here](https://github.com/YingZhangDUT/Cross-Modal-Projection-Learning), which is implemented by Tensorflow.
The repo is an unofficial PyTorch implementation for the paper.

**Comment by FlyingRoastDuck** [comment]
Thank you
