### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by lbmili2018** [labyrinth7x/Deep-Cross-Modal-Projection-Learning-for-Image-Text-Matching#2]
I didn't find CUHK-PEDES dataset, please upload.

**Comment by labyrinth7x** [comment]
The repo is an unofficial implementation for the paper by PyTorch. The official implementation is [here](https://github.com/YingZhangDUT/Cross-Modal-Projection-Learning) which is implemented by Tensorflow. And the paper which publishes the dataset is [here](https://github.com/ShuangLI59/Person-Search-with-Natural-Language-Description). You should ask the authors to get the access to CUHK-PEDES.
